on:
  push:
    branches: main
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and deploy Book

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/structuralequationmodels/sem-talk:main
    steps:
      - 
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Render book to all formats
        run: make
